resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/Ruchita7/demo.git
      branch: main
jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true
      - task: mvn-test
        file: "source-code/maven-test.yml"

